### ISSUE TITLE
启动时报错Failed to import "nonebot_plugin_apscheduler"

### ISSUE THREAD

**Issue by 19231224lhr** [CMHopeSunshine/LittlePaimon#310]
我将很多其他插件也加进了小派蒙，但是启动后出现这个问题
![image](https://user-images.githubusercontent.com/70199004/196996421-c8663401-3f8b-4e64-a244-2bebea64e9e2.png)

主要插件的报错
![image](https://user-images.githubusercontent.com/70199004/196996611-feef4ded-7853-4cd6-82a8-9514e3bc4c22.png)
![image](https://user-images.githubusercontent.com/70199004/196996737-8878fe76-8f4c-4988-9bbb-e73c8f20b0cd.png)
好像调用了`nonebot_plugin_apscheduler`插件的都报错了呜呜
![image](https://user-images.githubusercontent.com/70199004/196997001-2e8b1c92-c657-48b1-b589-cedc40e594b3.png)

其实我自己建的机器人也遇到了这个问题，好像是因为版本的问题，于是我尝试了`pip install --upgrade nonebot_plugin_apscheduler`，最后问题就解决了，但是在小派蒙项目中，我这样执行还是有问题呜呜

这是我加入的插件
![image](https://user-images.githubusercontent.com/70199004/196997446-3d0164f4-e1c4-4743-9b93-ef01999f65cc.png)

**Comment by CMHopeSunshine** [comment]
试试在`load_plugin("LittlePaimon")`上一行加一句`load_plugin("nonebot_plugin_apscheduler")`

**Comment by 19231224lhr** [comment]
> 试试在`load_plugin("LittlePaimon")`上一行加一句`load_plugin("nonebot_plugin_apscheduler")`

还是报了一样的错呜呜

![image](https://user-images.githubusercontent.com/70199004/196999250-d0934079-91e1-461a-a63c-cba7c7b8304f.png)
![image](https://user-images.githubusercontent.com/70199004/196999825-62ed7dc4-cc15-4f4f-a47a-7c5f52703736.png)

**Comment by CMHopeSunshine** [comment]
更新一下版本，`poetry run pip install nonebot-plugin-apscheduler -U`

**Comment by 19231224lhr** [comment]
好的，我马上去试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月21日(周五) 上午10:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CMHopeSunshine/LittlePaimon] 启动时报错Failed to import "nonebot_plugin_apscheduler" (Issue #310)

**Comment by ERICK886** [comment]
PS C:\Paimon\LittlePaimon> & C:/Python311/python.exe c:/Paimon/LittlePaimon/bot.py
12-19 11:22:35 [SUCCESS] nonebot | NoneBot is initializing...
12-19 11:22:35 [INFO] nonebot | Current Env: prod
12-19 11:22:35 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets"
12-19 11:22:35 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler"
12-19 11:22:35 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange"
12-19 11:22:35 [ERROR] nonebot | Failed to import "LittlePaimon"
Traceback (most recent call last):
  File "c:\Paimon\LittlePaimon\bot.py", line 28, in <module>
    nonebot.load_plugin("LittlePaimon")
  File "C:\Python311\Lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\Paimon\LittlePaimon\LittlePaimon\__init__.py", line 5, in <module>
    from LittlePaimon import database, web
  File "c:\Paimon\LittlePaimon\LittlePaimon\database\__init__.py", line 9, in <module>
    from .models import *
  File "c:\Paimon\LittlePaimon\LittlePaimon\database\models\__init__.py", line 1, in <module>
    from .character import *
  File "c:\Paimon\LittlePaimon\LittlePaimon\database\models\character.py", line 5, in <module>
    from tortoise import fields
ImportError: cannot import name 'fields' from 'tortoise' (C:\Python311\Lib\site-packages\tortoise\__init__.py)
12-19 11:22:35 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
12-19 11:22:35 [SUCCESS] nonebot | Running NoneBot...
12-19 11:22:35 [INFO] logging | Started server process [23828]
12-19 11:22:35 [INFO] logging | Waiting for application startup.
12-19 11:22:35 [INFO] nonebot_plugin_apscheduler | Scheduler Started
12-19 11:22:35 [INFO] LittlePaimon | Scheduler Started
12-19 11:22:35 [INFO] logging | Application startup complete.
12-19 11:22:35 [INFO] logging | Uvicorn running on http://0.0.0.0:13579 (Press CTRL+C to quit)
12-19 11:22:38 [INFO] logging | ('127.0.0.1', 55687) - "WebSocket /onebot/v11/ws" [accepted]
12-19 11:22:38 [INFO] nonebot | OneBot V11 | Bot 2559987819 connected
12-19 11:22:38 [INFO] logging | connection open

**Comment by ERICK886** [comment]
> PS C:\Paimon\LittlePaimon> & C:/Python311/python.exe c:/Paimon/LittlePaimon/bot.py 12-19 11:22:35 [SUCCESS] nonebot | NoneBot is initializing... 12-19 11:22:35 [INFO] nonebot | Current Env: prod 12-19 11:22:35 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_couplets" 12-19 11:22:35 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_apscheduler" 12-19 11:22:35 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_myb_exchange" 12-19 11:22:35 [ERROR] nonebot | Failed to import "LittlePaimon" Traceback (most recent call last): File "c:\Paimon\LittlePaimon\bot.py", line 28, in nonebot.load_plugin("LittlePaimon") File "C:\Python311\Lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin return manager.load_plugin(module_path)
> 
> > File "C:\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
> > module = importlib.import_module(name)
> > File "C:\Python311\Lib\importlib__init__.py", line 126, in import_module
> > return _bootstrap._gcd_import(name[level:], package, level)
> > File "", line 1206, in _gcd_import
> > File "", line 1178, in _find_and_load
> > File "", line 1149, in _find_and_load_unlocked
> > File "", line 690, in _load_unlocked
> > File "C:\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
> > super().exec_module(module)
> > File "", line 940, in exec_module
> > File "", line 241, in _call_with_frames_removed
> > File "c:\Paimon\LittlePaimon\LittlePaimon__init__.py", line 5, in 
> > from LittlePaimon import database, web
> > File "c:\Paimon\LittlePaimon\LittlePaimon\database__init__.py", line 9, in 
> > from .models import *
> > File "c:\Paimon\LittlePaimon\LittlePaimon\database\models__init_.py", line 1, in 
> > from .character import *
> > File "c:\Paimon\LittlePaimon\LittlePaimon\database\models\character.py", line 5, in 
> > from tortoise import fields
> > ImportError: cannot import name 'fields' from 'tortoise' (C:\Python311\Lib\site-packages\tortoise__init_.py)
> > 12-19 11:22:35 [WARNING] **main** | Always use `nb run` to start the bot instead of manually running!
> > 12-19 11:22:35 [SUCCESS] nonebot | Running NoneBot...
> > 12-19 11:22:35 [INFO] logging | Started server process [23828]
> > 12-19 11:22:35 [INFO] logging | Waiting for application startup.
> > 12-19 11:22:35 [INFO] nonebot_plugin_apscheduler | Scheduler Started
> > 12-19 11:22:35 [INFO] LittlePaimon | Scheduler Started
> > 12-19 11:22:35 [INFO] logging | Application startup complete.
> > 12-19 11:22:35 [INFO] logging | Uvicorn running on http://0.0.0.0:13579 (Press CTRL+C to quit)
> > 12-19 11:22:38 [INFO] logging | ('127.0.0.1', 55687) - "WebSocket /onebot/v11/ws" [accepted]
> > 12-19 11:22:38 [INFO] nonebot | OneBot V11 | Bot 2559987819 connected
> > 12-19 11:22:38 [INFO] logging | connection open__

这个是什么问题呀，我用了`poetry install`也没用

**Comment by CMHopeSunshine** [comment]
> 
是否在bot目录中运行的呢？使用的启动命令是什么
